#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Tue Nov  3 09:05:41 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class AboutDialog(wx.Dialog):
    description = "Describe your project"
    details = "Add details"

    def __init__(self, *args, **kwds):
        # begin wxGlade: AboutDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.about_text = wx.StaticText(self, wx.ID_ANY, "label_1")
        self.about2_text = wx.StaticText(self, wx.ID_ANY, "label_2")
        self.Ok_button = wx.Button(self, wx.ID_ANY, "button_1")
        self.Bind(wx.EVT_BUTTON, self.click_ok, id=self.Ok_button.GetId())

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AboutDialog.__set_properties
        self.SetTitle("About Lottery Analysis")
        self.about_text.SetLabel(self.description)
        self.about2_text.SetLabel(self.details)
        self.Ok_button.SetLabel("OK")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AboutDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.about_text, 0, 0, 0)
        sizer_1.Add(self.about2_text, 0, 0, 0)
        sizer_1.Add(self.Ok_button, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def set_description(self, str_description):
        self.description = str_description

    def set_details(self, str_details):
        self.details = str_details

    def click_ok(self, event):
        self.Close()

# end of class AboutDialog

