#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Tue Nov  3 07:22:58 2020
#

import wx
import wx.grid
import AboutDialog
import database

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((692, 485))
        self.grid_1 = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        
        # Menu Bar
        self.frame_menubar_copy = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Load Data", "Load or reload data from database")
        self.Bind(wx.EVT_MENU, self.DoLoadData, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Save Data", "Save any changes")
        self.Bind(wx.EVT_MENU, self.DoSaveData, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Exit", "Bye!")
        self.Bind(wx.EVT_MENU, self.ExitApp, id=item.GetId())
        self.frame_menubar_copy.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar_copy.Append(wxglade_tmp_menu, "Edit")
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "About", "")
        self.Bind(wx.EVT_MENU, self.DoAboutDialog, id=item.GetId())
        self.frame_menubar_copy.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.frame_menubar_copy)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()
        self.db_instance = database.database("localhost", "tim", "@sim0v73")


        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Lottery Analysis")
        self.grid_1.CreateGrid(10, 7)
        self.grid_1.SetColLabelValue(0, "Date")
        self.grid_1.SetColLabelValue(1, "First")
        self.grid_1.SetColLabelValue(2, "Second")
        self.grid_1.SetColLabelValue(3, "Third")
        self.grid_1.SetColLabelValue(4, "Fourth")
        self.grid_1.SetColLabelValue(5, "Fifth")
        self.grid_1.SetColLabelValue(6, "Powerball")
        frame_1_statusbar_fields = ["frame_1_statusbar"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.grid_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def DoLoadData(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'DoLoadData' not implemented!")
        event.Skip()

    def DoSaveData(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'DoSaveData' not implemented!")
        event.Skip()

    def ExitApp(self, event):  # wxGlade: MyFrame.<event_handler>
        #print("Event handler 'ExitApp' not implemented!")
        wx.Exit()
        event.Skip()

    def DoAboutDialog(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'DoAboutDialog' not implemented!")
        about_me = AboutDialog.AboutDialog(self)
        about_me.set_description("Analysis of the lottery")
        about_me.set_details("Programmer: Tim Davis\nRedesigned 04 Nov 2020")
        about_me.Show()
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
