#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Sun Nov 15 15:39:49 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class AboutDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AboutDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_4 = wx.Panel(self, wx.ID_ANY)
        self.about_text = wx.StaticText(self.panel_4, wx.ID_ANY, "Title", style=wx.ALIGN_LEFT)
        self.about_title_txt = wx.TextCtrl(self.panel_4, wx.ID_ANY, "")
        self.panel_5 = wx.Panel(self, wx.ID_ANY)
        self.about2_text = wx.StaticText(self.panel_5, wx.ID_ANY, "About project:")
        self.about_about_txt = wx.TextCtrl(self.panel_5, wx.ID_ANY, "What your project is about")
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.Ok_button_copy_copy = wx.Button(self.panel_1, wx.ID_ANY, "button_1")
        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AboutDialog.__set_properties
        self.SetTitle("dialog")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AboutDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.about_text, 0, wx.ALIGN_CENTER, 0)
        sizer_3.Add(self.about_title_txt, 0, wx.ALIGN_CENTER, 0)
        self.panel_4.SetSizer(sizer_3)
        sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)
        sizer_4.Add(self.about2_text, 0, 0, 0)
        sizer_4.Add(self.about_about_txt, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL | wx.EXPAND, 0)
        self.panel_5.SetSizer(sizer_4)
        sizer_1.Add(self.panel_5, 1, wx.EXPAND, 0)
        sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        sizer_2.Add(self.Ok_button_copy_copy, 0, wx.ALIGN_CENTER, 0)
        sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class AboutDialog

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = AboutDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
